---
title: "Code for Figure 3.4:Comparison of two combined strategies when one resource is limiting "
output: A plot of Case 2 and Case 3 for limiting and non-limiting resources.
---

```{r}
require(deSolve)
require(ggplot2)
require(patchwork)
cols <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#66CC99")



##### Parameters
# max daily rate of community member isolation
u1max <- 0.6

# max daily rate of traveler isolation
u2max <- 1.3

# constraint on community member isolation
C1max <- 500

# constraint on traveller isolation
C2max <- 100

# transmission rate
beta<-.0002

# importation rate
theta <- 1

mu<-0.334

gamma <- 2*mu

# relative transmissibility of travellers
c<-1

T <- 2000


# start time for community isolation
tstart1<-0

# in case we wanted to do two switches
toff1 <- 2000 # currently set to not turn-off

# start time for restrictions on travellers
tstart2 <- 0
toff2 <- 2000

# community isolation function
u1fun<-function(t){
  u1 = u1max
  if(t<tstart1){
  u1 = 0}
  if(t<(toff1+10) & t>toff1){
    u1 = 0
  }
  return(u1)
}

# travel restrictions function
u2fun<-function(t){
  u2 = u2max
  if(t < tstart2){
  u2 = 0}
  if( t > toff2 & t < (toff2+5)){
    u2 = 0
  }
  return(u2)
}

# This is designed to trigger termination of the simulation when I1>0.5
rootfun <- function(t, y, parameters){
  I1 = y[2]
  # However, with importations, it doesn't make sense to have this as
  # the endpoint of the simulation, so instead I just set Imin = 0 and have
  # the simulation end at T=100.
  y1 = 1 - I1 
  return(y1)
}


SI<-function(t, y, parameters){
  S = y[1]
  I1 = y[2]
  I2 = y[3]
  C1 = y[4]
  C2 = y[5]
  iso1 = y[6]
  iso2 = y[7]
  u1 = u1fun(t)
  u2 = u2fun(t)
  
  if(C1 > C1max){
    u1 = 0
  }
  if(C2 > C2max){
    u2 = 0
  }
  
  dS = - beta*S*(I1 + c*I2)
  dI1 = beta*S*(I1 + c*I2) - mu*I1 - u1*I1
  dI2 = theta - 2*mu*I2 - u2*I2
  dC1 = u1*I1
  dC2 = u2*I2
  diso1 = u1*I1 - mu*iso1
  diso2 = u2*I2 - 2*mu*iso2
  return(list(c(dS,dI1,dI2,dC1,dC2,diso1,diso2)))
}


### CASE 2: CR limiting

C1max <- 500
C2max <- 100


out1 <- ode(y = c(S=5000, I1=10, I2= theta/((2*mu) + u2max), C1=0, C2=0, iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)

out1 <- data.frame(out1)
out.cs1 <- data.frame(out1)

J = cumsum(beta*out1$S*(out1$I1+c*out1$I2)*diff(c(0,out1$time)))
J.cs1 <- J

u = rep(0,length(J))
u[which(diff(c(out1$C1[1],out1$C1))*diff(c(0,out1$time))>0.00001)] = max(c(out1$I1,out1$iso1))

u.1 = rep(0,length(J))
u.1[which(diff(c(out1$C2[1],out1$C2))*diff(c(0,out1$time))>0.001)] = max(c(out1$I2,out1$iso2))

out.cs1 <- data.frame(out1,u=u, u.1 = u.1, j =J )


final_time <- tail(out.cs1$time, 1)


#plot J
g.J = ggplot(out.cs1, aes(x = time, y = j)) +
  geom_line(color = cols[8], size = 2)+
  geom_point(aes(x = final_time, y = max(out.cs1$j)), color = "red", size = 3) +
  geom_vline(aes(xintercept = final_time), color = "red", linetype = "dashed")  +
  geom_hline(aes(yintercept = max(out.cs1$j)), color = "red", linetype = "dashed")  +
  ggtitle(" ")+ylab(expression(paste("cumulative number of new infections"))) + xlim(0,100)+theme_classic() +
  annotate("text", x = 70, y = max(out.cs1$j), label = expression(J), hjust = -0.2, vjust = -0.3, color = "black", size = 8) +
  scale_x_continuous(breaks = seq(min(out.cs1$time), max(out.cs1$time), by = 10)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



#plot U1
g.U1 = ggplot(out.cs1, aes(x = time, y = C1)) +
  geom_line(color = cols[8], size = 2) + 
  geom_point(aes(x = final_time, y = C1max), color = "red", size = 3) +
  geom_vline(aes(xintercept = final_time), color = "red", linetype = "dashed")  +
  geom_hline(aes(yintercept = C1max), color = "black", linetype = "dotted")  +
  annotate("text", x = 40, y = 500, label = expression(paste(U[1](T))), hjust = -0.2, vjust = -0.3, color = "black", size = 8) +
  annotate("text", x = 65, y = 500, label = expression(paste( U[1][max])), hjust = -0.2, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative community members isolated"))) + xlim(0,100)+theme_classic() + scale_x_continuous(breaks = seq(min(out.cs1$time), max(out.cs1$time), by = 10)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



#plot U2
g.U2 = ggplot(out.cs1, aes(x = time, y = C2)) +
  geom_line(color = cols[8], size = 2)+ 
  geom_point(aes(x = final_time, y = max(out.cs1$C2)), color = "red", size = 3) +
  geom_segment(aes(x = final_time, xend = final_time, y = 0, yend = max(out.cs1$C2)), color = "red", linetype = "dashed") +
  geom_segment(aes(x = 0, xend = final_time, y = max(out.cs1$C2), yend = max(out.cs1$C2)), color = "red", linetype = "dashed") +
  scale_x_continuous(breaks = seq(min(out.cs1$time), max(out.cs1$time), by = 10)) +
  geom_hline(aes(yintercept = C2max), color = "black", linetype = "dotted")  + 
  annotate("text", x = 60, y = max(out.cs1$C2), label = expression(paste(U[2](T))), hjust = -0.2, vjust = -0.3, color = "black", size = 8) +
  annotate("text", x = 65, y = C2max, label = expression(paste(U[2][max])), hjust = -0.2, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative travelers isolated"))) + xlim(0,100)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs1$time),max(out.cs1$time), by = 10)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



g.cs1 = g.J + g.U1 + g.U2
g.cs1
final_time

```


```{r}

#plot community infections
#g.I1 = ggplot(out.cs1, aes(x = time, y = I1)) + 
  #geom_ribbon(aes(ymin = 0, ymax = u), fill = cols[9], alpha = 0.2)+
  #geom_line(color = cols[9], size = 2)+ 
  #ggtitle(" ")+ylab("Community prevalence") + xlim(0,100)+theme_classic() +
  #theme(
  #plot.title = element_text(size = 20),       # Title size
  #axis.title = element_text(size = 30),       # Axis title size
  #axis.text = element_text(size = 30),        # Axis text size
  #legend.title = element_text(size = 20),     # Legend title size
  #legend.text = element_text(size = 20) )      # Legend text size

#g.I1
```




```{r}
###Circuit breaker, \tilde{u}_1

C1max <- 500
C2max <- 100

toff1 <- 5
u1max <- 0.4



out1_1 <- ode(y = c(S=5000, I1=10, I2= theta/((2*mu) + u2max), C1=0, C2=0, iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)

out1_1 <- data.frame(out1_1)
out.cs1_1 <- data.frame(out1_1)

J = cumsum(beta*out1_1$S*(out1_1$I1+c*out1_1$I2)*diff(c(0,out1_1$time)))
J.cs1_1 <- J

u = rep(0,length(J))
u[which(diff(c(out1_1$C1[1],out1_1$C1))*diff(c(0,out1_1$time))>0.00001)] = max(c(out1_1$I1,out1_1$iso1))

u.1 = rep(0,length(J))
u.1[which(diff(c(out1_1$C2[1],out1_1$C2))*diff(c(0,out1_1$time))>0.001)] = max(c(out1_1$I2,out1_1$iso2))

out.cs1_1 <- data.frame(out1_1,u=u, u.1 = u.1, j =J )


final_time_1 <- tail(out.cs1_1$time, 1)

#plot J
g.J_1 = ggplot(out.cs1_1, aes(x = time, y = j)) +
  geom_line(color = cols[6], size = 2)+
  geom_point(aes(x = final_time_1, y = max(out.cs1_1$j)), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_1), color = "black", linetype = "dashed")  +
  geom_hline(aes(yintercept = max(out.cs1_1$j)), color = "black", linetype = "dashed")  +
  ggtitle(" ")+ylab(expression(paste("cumulative number of new infections"))) + xlim(0,70)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs1_1$time), max(out.cs1_1$time), by = 10)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size


#plot U1
g.U1_1 = ggplot(out.cs1_1, aes(x = time, y = C1)) +
  geom_line(color = cols[6], size = 2)+
  geom_hline(aes(yintercept = C1max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_1, y = C1max), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_1), color = "black", linetype = "dashed")  +
  annotate("text", x = 40, y = 500, label = expression(paste(U[1][max])), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative community members isolated"))) + xlim(0,70)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs1_1$time), max(out.cs1_1$time), by = 10)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



#plot U2
g.U2_1 = ggplot(out.cs1_1, aes(x = time, y = C2)) +
  geom_line(color = cols[6], size = 2)+
  geom_hline(aes(yintercept = C2max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_1, y = max(out.cs1_1$C2)), color = "black", size = 3) +
  geom_segment(aes(x = final_time_1, xend = final_time_1, y = 0, yend = max(out.cs1_1$C2)), color = "black", linetype = "dashed") +
  geom_segment(aes(x = 0, xend = final_time_1, y = max(out.cs1_1$C2)), yend = max(out.cs1_1$C2), color = "black", linetype = "dashed") +
  annotate("text", x = 40, y = C2max, label = expression(paste(U[2][max])), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative travelers isolated"))) + xlim(0,70)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs1_1$time), max(out.cs1_1$time), by = 10)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



g.cs1_1 = g.J_1 + g.U1_1 + g.U2_1
g.cs1_1
final_time_1

```


```{r}

#plot community infections
#g.I1_1 = ggplot(out.cs1_1, aes(x = time, y = I1)) + 
  #geom_ribbon(aes(ymin = 0, ymax = u), fill = cols[9], alpha = 0.2)+
  #geom_line(color = cols[9], size = 2)+ 
  #ggtitle(" ")+ylab("Community prevalence") + xlim(0,100)+theme_classic() +
  #theme(
  #plot.title = element_text(size = 20),       # Title size
  #axis.title = element_text(size = 30),       # Axis title size
  #axis.text = element_text(size = 30),        # Axis text size
  #legend.title = element_text(size = 20),     # Legend title size
  #legend.text = element_text(size = 20) )      # Legend text size

#g.I1_1
```




```{r}

##### Parameters
# max daily rate of community member isolation
u1max <- 0.6

# max daily rate of traveler isolation
u2max <- 1.3

# constraint on community member isolation
U1max <- 2500

# constraint on traveller isolation
U2max <- 200

# transmission rate
beta<-.0002

# importation rate
theta <- 1

mu<-0.334

gamma <- 2*mu

# relative transmissibility of travellers
c<-1

T<-2000


# start time for community isolation
tstart1<-0

# in case we wanted to do two switches
toff1 <- 2000 # currently set to not turn-off

# start time for restrictions on travellers
tstart2 <- 0
toff2 <- 2000

# community isolation function
u1fun<-function(t){
  u1 = u1max
  if(t<tstart1){
  u1 = 0}
  if(t<(toff1+5) & t>toff1){
    u1 = 0
  }
  return(u1)
}

# travel restrictions function
u2fun<-function(t){
  u2 = u2max
  if(t < tstart2){
  u2 = 0}
  if( t > toff2 & t < (toff2+100)){
    u2 = 0
  }
  return(u2)
}

# This is designed to trigger termination of the simulation when I1>0.5
rootfun <- function(t, y, parameters){
  I1 = y[2]
  # However, with importations, it doesn't make sense to have this as
  # the endpoint of the simulation, so instead I just set Imin = 0 and have
  # the simulation end at T=100.
  y1 = 1 - I1 
  return(y1)
}


SI<-function(t, y, parameters){
  S = y[1]
  I1 = y[2]
  I2 = y[3]
  U1 = y[4]
  U2 = y[5]
  iso1 = y[6]
  iso2 = y[7]
  u1 = u1fun(t)
  u2 = u2fun(t)
  
  if(U1 > U1max){
    u1 = 0
  }
  if(U2 > U2max){
    u2 = 0
  }
  
  dS = - beta*S*(I1 + c*I2)
  dI1 = beta*S*(I1 + c*I2) - mu*I1 - u1*I1
  dI2 = theta - 2*mu*I2 - u2*I2
  dU1 = u1*I1
  dU2 = u2*I2
  diso1 = u1*I1 - mu*iso1
  diso2 = u2*I2 - 2*mu*iso2
  return(list(c(dS,dI1,dI2,dU1,dU2,diso1,diso2)))
}


### CASE 3: TR Limiting
T <- 2000
U1max <- 2500
U2max <- 200


out <- ode(y = c(S=5000, I1=10, I2= theta/((2*mu) + u2max), U1=0, U2=0, iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)

out <- data.frame(out)
out.cs2 <- data.frame(out)

J = cumsum(beta*out$S*(out$I1+c*out$I2)*diff(c(0,out$time)))
J.cs2 <- J

u = rep(0,length(J))
u[which(diff(c(out$U1[1],out$U1))*diff(c(0,out$time))>0.00001)] = max(c(out$I1,out$iso1))

u.1 = rep(0,length(J))
u.1[which(diff(c(out$U2[1],out$U2))*diff(c(0,out$time))>0.001)] = max(c(out$I2,out$iso2))

out.cs2 <- data.frame(out,u=u, u.1 = u.1, j =J )


final_time_2 <- tail(out.cs2$time, 1)

#plot J
g.J_2 = ggplot(out.cs2, aes(x = time, y = j)) +
  geom_line(color = cols[8], size = 2)+
  geom_point(aes(x = final_time_2, y = max(out.cs2$j)), color = "red", size = 3) +
  geom_vline(aes(xintercept = final_time_2), color = "red", linetype = "dashed")  +
  geom_hline(aes(yintercept = max(out.cs2$j)), color = "red", linetype = "dashed")  +
  ggtitle(" ")+ylab(expression(paste("cumulative number of new infections "))) + xlim(0,1300)+theme_classic() +
  annotate("text", x = 900, y = max(out.cs2$j), label = expression(J), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  scale_x_continuous(breaks = seq(min(out.cs2$time), max(out.cs2$time), by = 200)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



#plot U1
g.U1_2 = ggplot(out.cs2, aes(x = time, y = U1)) +
  geom_line(color = cols[8], size = 2)+
  geom_hline(aes(yintercept = U1max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_2, y = max(out.cs2$U1)), color = "red", size = 3) +
  geom_segment(aes(x = final_time_2, xend = final_time_2, y = 0, yend = max(out.cs2$U1)), color = "red", linetype = "dashed") +
  geom_segment(aes(x = 0, xend = final_time_2, y = max(out.cs2$U1), yend = max(out.cs2$U1)), color = "red", linetype = "dashed") +
  annotate("text", x = 900, y = U1max, label = expression(paste(U[1][max])), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  annotate("text", x = 900, y = max(out.cs2$U1), label = expression(paste(U[1](T))), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative community members isolated"))) + xlim(0,1300)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs2$time), max(out.cs2$time), by = 200)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



#plot U2
g.U2_2 = ggplot(out.cs2, aes(x = time, y = U2)) +
  geom_line(color = cols[8], size = 2)+
  geom_hline(aes(yintercept = U2max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_2, y = U2max), color = "red", size = 3) +
  geom_vline(aes(xintercept = final_time_2), color = "red", linetype = "dashed")  +
  annotate("text", x = 900, y = U2max, label = expression(paste(U[2][max])), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  annotate("text", x = 400, y = U2max, label = expression(paste(U[2](T))), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative travelers isolated"))) + xlim(0,1300)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs2$time), max(out.cs2$time), by = 200)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



g.cs2 = g.J_2 + g.U1_2 + g.U2_2
g.cs2
final_time_2

```


```{r}

#plot traveler infections
#g.I2 = ggplot(out.cs2, aes(x = time, y = I2)) + 
  #geom_ribbon(aes(ymin = 0, ymax = u.1), fill = cols[9], alpha = 0.2)+
  #geom_line(color = cols[9], size = 2)+ 
  #ggtitle(" ")+ylab("traveler prevalence") + xlim(0,1500)+theme_classic() +
  #theme(
  #plot.title = element_text(size = 20),       # Title size
  #axis.title = element_text(size = 30),       # Axis title size
  #axis.text = element_text(size = 30),        # Axis text size
  #legend.title = element_text(size = 20),     # Legend title size
  #legend.text = element_text(size = 20) )      # Legend text size

#g.I2
```



```{r}
### circuit breaker, \tilde{u}_2

U1max <- 2500
U2max <- 200

toff2 <- 200

u2max <- 0.5

out2 <- ode(y = c(S=5000, I1=10, I2= theta/((2*mu) + u2max), U1=0, U2=0, iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)

out2 <- data.frame(out2)
out.cs2_1 <- data.frame(out2)

J = cumsum(beta*out2$S*(out2$I1+c*out2$I2)*diff(c(0,out2$time)))
J.cs2 <- J

u = rep(0,length(J))
u[which(diff(c(out2$U1[1],out2$U1))*diff(c(0,out2$time))>0.00001)] = max(c(out2$I1,out2$iso1))

u.1 = rep(0,length(J))
u.1[which(diff(c(out2$U2[1],out2$U2))*diff(c(0,out2$time))>0.001)] = max(c(out2$I2,out2$iso2))

out.cs2_1 <- data.frame(out2,u=u, u.1 = u.1, j =J )

# Getting the time values 

final_time_3 <- tail(out.cs2_1$time, 1)

#plot J
g.J_2_1 = ggplot(out.cs2_1, aes(x = time, y = j)) +
  geom_line(color = cols[6], size = 2)+
  geom_point(aes(x = final_time_3, y = max(out.cs2_1$j)), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_3), color = "black", linetype = "dashed")  +
  geom_hline(aes(yintercept = max(out.cs2_1$j)), color = "black", linetype = "dashed")  +
  ggtitle(" ")+ylab(expression(paste("cumulative number of new infections"))) + xlim(0,1300)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs2_1$time), max(out.cs2_1$time), by = 200)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size


#plot U1
g.U1_2_1 = ggplot(out.cs2_1, aes(x = time, y = U1)) +
  geom_line(color = cols[6], size = 2)+
  geom_hline(aes(yintercept = U1max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_3, y = max(out.cs2_1$U1)), color = "black", size = 3) +
  geom_segment(aes(x = final_time_3, xend = final_time_3, y = 0, yend = max(out.cs2_1$U1)), color = "black", linetype = "dashed") +
  geom_segment(aes(x = 0, xend = final_time_3, y = max(out.cs2_1$U1), yend = max(out.cs2_1$U1)), color = "black", linetype = "dashed") +
  annotate("text", x = 900, y = U1max, label = expression(paste(U[1][max])), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative community members isolated"))) + xlim(0,1300)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs2_1$time), max(out.cs2_1$time), by = 200)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



#plot U2
g.U2_2_1 = ggplot(out.cs2_1, aes(x = time, y = U2)) +
  geom_line(color = cols[6], size = 2)+
  geom_hline(aes(yintercept = U2max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_3, y = U2max), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_3), color = "black", linetype = "dashed")  +
  annotate("text", x = 900, y = U2max, label = expression(paste(U[2][max])), hjust = -0.1, vjust = -0.3, color = "black", size = 8) +
  ggtitle(" ")+ylab(expression(paste("cumulative travelers isolated"))) + xlim(0,1300)+theme_classic() +
  scale_x_continuous(breaks = seq(min(out.cs2_1$time), max(out.cs2_1$time), by = 200)) +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size



g.cs2_1 = g.J_2_1 + g.U1_2_1 + g.U2_2_1
g.cs2_1
final_time_3


```


```{r}

#plot traveler infections
#g.I2_1 = ggplot(out.cs2_1, aes(x = time, y = I2)) + 
  #geom_ribbon(aes(ymin = 0, ymax = u.1), fill = cols[9], alpha = 0.2)+
  #geom_line(color = cols[9], size = 2)+ 
  #ggtitle(" ")+ylab("traveler prevalence") + xlim(0,1500)+theme_classic() +
  #theme(
  #plot.title = element_text(size = 20),       # Title size
  #axis.title = element_text(size = 30),       # Axis title size
  #axis.text = element_text(size = 30),        # Axis text size
  #legend.title = element_text(size = 20),     # Legend title size
  #legend.text = element_text(size = 20) )      # Legend text size

#g.I2_1
```



```{r}
require(deSolve)
require(ggplot2)
require(patchwork)

# Ensure you have the cols defined
cols <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#66CC99")

# Use your provided simulation and plotting code here to create the following ggplot objects:
# g.J, g.J_1, g.U1, g.U1_1, g.U2, g.U2_1
# g.J_2, g.J_2_1, g.U1_2, g.U1_2_1, g.U2_2, g.U2_2_1

# Now combine the plots accordingly

# A: Combine g.J and g.J_1
combined_J <- g.J + geom_line(data = out.cs1_1, aes(x = time, y = J.cs1_1), color = cols[3], size = 2) +
  geom_point(aes(x = final_time_1, y = max(out.cs1_1$j)), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_1), color = "black", linetype = "dashed")  +
  geom_hline(aes(yintercept = max(out.cs1_1$j)), color = "black", linetype = "dashed")

# B: Combine g.U1 and g.U1_1
combined_U1 <- g.U1 + geom_line(data = out.cs1_1, aes(x = time, y = C1), color = cols[3], size = 2) + 
  geom_hline(aes(yintercept = C1max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_1, y = C1max), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_1), color = "black", linetype = "dashed")


# C: Combine g.U2 and g.U2_1
combined_U2 <- g.U2 + geom_line(data = out.cs1_1, aes(x = time, y = C2), color = cols[3], size = 2) +
  geom_hline(aes(yintercept = C2max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_1, y = max(out.cs1_1$C2)), color = "black", size = 3) +
  geom_segment(aes(x = final_time_1, xend = final_time_1, y = 0, yend = max(out.cs1_1$C2)), color = "black", linetype = "dashed") +
  geom_segment(aes(x = 0, xend = final_time_1, y = max(out.cs1_1$C2)), yend = max(out.cs1_1$C2), color = "black", linetype = "dashed")+
  annotate("text", x = 30, y = max(out.cs1_1$C2), label = expression(paste(U[2](T))), hjust = -0.1, vjust = -0.3, color = "black", size = 8)
  

# D: Combine g.J_2 and g.J_2_1
combined_J2 <- g.J_2 + geom_line(data = out.cs2_1, aes(x = time, y = J), color = cols[3], size = 2) +
  geom_point(aes(x = final_time_3, y = max(out.cs2_1$j)), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_3), color = "black", linetype = "dashed")  +
  geom_hline(aes(yintercept = max(out.cs2_1$j)), color = "black", linetype = "dashed")

# E: Combine g.U1_2 and g.U1_2_1
combined_U1_2 <- g.U1_2 + geom_line(data = out.cs2_1, aes(x = time, y = U1), color = cols[3], size = 2) + geom_hline(aes(yintercept = U1max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_3, y = max(out.cs2_1$U1)), color = "black", size = 3) +
  geom_segment(aes(x = final_time_3, xend = final_time_3, y = 0, yend = max(out.cs2_1$U1)), color = "black", linetype = "dashed") +
  geom_segment(aes(x = 0, xend = final_time_3, y = max(out.cs2_1$U1), yend = max(out.cs2_1$U1)), color = "black", linetype = "dashed")

# F: Combine g.U2_2 and g.U2_2_1
combined_U2_2 <- g.U2_2 + geom_line(data = out.cs2_1, aes(x = time, y = U2), color = cols[3], size = 2) + geom_hline(aes(yintercept = U2max), color = "black", linetype = "dotted")  + 
  geom_point(aes(x = final_time_3, y = U2max), color = "black", size = 3) +
  geom_vline(aes(xintercept = final_time_3), color = "black", linetype = "dashed")

# Display the combined plots
combined_J
combined_U1
combined_U2
combined_J2
combined_U1_2
combined_U2_2


```


```{r}

g.combined <- (combined_J + combined_U1 + combined_U2)/ (combined_J2 + combined_U1_2 + combined_U2_2) + plot_annotation(tag_levels = 'a') & theme(plot.tag = element_text(size = 25))


g.combined
```