---
title: "Code for Figure 4.2:The optimal controls categorized as different types of public health strate-
gies for the combined strategie"

---

```{r}
require(deSolve)
require(ggplot2)
require(patchwork)
cols <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#66CC99")

### The aim of this code is to make a figure that illustrates
### the isolation-only strategy in terms of Hansen & Day
### in terms of the public health terminology that I defined
#### elimination, suppression, and circuit breaker.


##### Parameters
# max daily rate of community member isolation
u1max <- 1.15

# max daily rate of traveler isolation
u2max <- 1.3

# constraint on community member isolation
C1max <- 1000

# constraint on traveller isolation
C2max <- 100

# transmission rate
beta<-.0002

# importation rate
theta <- 1

mu<-0.334

gamma <- 2*mu

# relative transmissibility of travellers
c<-1

T<-1000


# start time for community isolation
tstart1<-0

# in case we wanted to do two switches
toff1 <- 1000 # currently set to not turn-off

# start time for restrictions on travellers
tstart2 <- 0
toff2 <- 1000

# community isolation function
u1fun<-function(t){
  u1 = u1max
  if(t<tstart1){
  u1 = 0}
  if(t<(toff1+5) & t>toff1){
    u1 = 0
  }
  return(u1)
}

# travel restrictions function
u2fun<-function(t){
  u2 = u2max
  if(t < tstart2){
  u2 = 0}
  if( t > toff2 & t < (toff2+5)){
    u2 = 0
  }
  return(u2)
}

# This is designed to trigger termination of the simulation when I1>0.5
rootfun <- function(t, y, parameters){
  I1 = y[2]
  # However, with importations, it doesn't make sense to have this as
  # the endpoint of the simulation, so instead I just set Imin = 0 and have
  # the simulation end at T=100.
  y1 = 1 - I1 
  return(y1)
}


SI<-function(t, y, parameters){
  S = y[1]
  I1 = y[2]
  I2 = y[3]
  C1 = y[4]
  C2 = y[5]
  iso1 = y[6]
  iso2 = y[7]
  u1 = u1fun(t)
  u2 = u2fun(t)
  
  if(C1 > C1max){
    u1 = 0
  }
  if(C2 > C2max){
    u2 = 0
  }
  
  dS = - beta*S*(I1 + c*I2)
  dI1 = beta*S*(I1 + c*I2) - mu*I1 - u1*I1
  dI2 = theta - 2*mu*I2 - u2*I2
  dC1 = u1*I1
  dC2 = u2*I2
  diso1 = u1*I1 - mu*iso1
  diso2 = u2*I2 - 2*mu*iso2
  return(list(c(dS,dI1,dI2,dC1,dC2,diso1,diso2)))
}


```





```{r}

###. Suppression

#(same parameters except a lower u1max)
u1max <- 0.2
u2max <- 1.3

C1max <- 1500
C2max <- 100


out <- ode(y = c(S=5000, I1=10, I2= 0, C1=0, C2=0, iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out <- data.frame(out)
out.supp<-data.frame(out)

J = cumsum(beta*out$S*(out$I1+c*out$I2)*diff(c(0,out$time)))
J.supp <- J

u = rep(0,length(J))
u[which(diff(c(out$C1[1],out$C1))*diff(c(0,out$time))>0.00001)] = max(c(out$I1,out$iso1))

u.1 = rep(0,length(J))
u.1[which(diff(c(out$C2[1],out$C2))*diff(c(0,out$time))>0.001)] = max(c(out$I2,out$iso2))

out.supp <- data.frame(out,u=u, u.1 = u.1, j =J )

#plot community cases
g.supp = ggplot(out.supp, aes(x = time, y = I1)) +
  geom_ribbon(aes(ymin = 0, ymax = u), fill = cols[2], alpha = 0.2)+
  geom_line(color = cols[2], size = 2)+
  ggtitle("Mitigation")+ylab("Community prevalence") + xlim(0,50)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.supp


#plot travel cases
g.supp1 = ggplot(out.supp, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u.1), fill = cols[2], alpha = 0.2)+
  geom_line(color = cols[2], size = 2)+
  ggtitle("Mitigation")+ylab("Traveller's prevalence") + xlim(0,50)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.supp1

gsupp = g.supp + g.supp1
gsupp

```



```{r}
###### SUPPRESSION/CIRCUIT BREAKER 

u1max <- 0.2
u2max <- 1.8

C1max <- 1500
C2max <- 30

toff1<-3000
toff2 <- 20

outsc <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0,iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
outsc <- data.frame(outsc)
out.sc<-outsc

J.sc = cumsum(beta*outsc$S*(outsc$I1+c*outsc$I2)*diff(c(0,outsc$time)))

u_2 = rep(0,length(J.sc))
u_2[which(diff(c(outsc$C1[1],outsc$C1))*diff(c(0,outsc$time))>0.0001)] = max(c(outsc$I1,outsc$iso1))

u_2.2 = rep(0,length(J.sc))
u_2.2[which(diff(c(outsc$C2[1],outsc$C2))*diff(c(0,outsc$time))>0.001)] = max(c(outsc$I2,outsc$iso2))

out.sc <- data.frame(outsc, u_2 = u_2, u_2.2 = u_2.2, j = J.sc)

#plot community infections
g.sc1 = ggplot(out.sc, aes(x = time, y = I1)) + 
  geom_ribbon(aes(ymin = 0, ymax = u_2), fill = cols[5], alpha = 0.2)+
  geom_line(color = cols[5], size = 2)+ 
  ggtitle("Mitigation")+ylab("Community prevalence") + xlim(0,50)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.sc1

#plot travel cases
g.sc2 = ggplot(out.sc, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_2.2), fill = cols[5], alpha = 0.2)+
  geom_line(color = cols[5], size = 2)+
  ggtitle("Circuit Breaker")+ylab("Traveller's prevalence") + xlim(0,50)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.sc2

gsc = g.sc1 + g.sc2
gsc

```




```{r}
###### CIRCUIT BREAKER/SUPPRESSION 

u1max <- 0.7
u2max <- 1.3

C1max <- 1000
C2max <- 100

toff1<-15
toff2 <- 70

out2 <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0,iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out2 <- data.frame(out2)
out.circ<-out2

J2 = cumsum(beta*out2$S*(out2$I1+c*out2$I2)*diff(c(0,out2$time)))

u_2 = rep(0,length(J2))
u_2[which(diff(c(out2$C1[1],out2$C1))*diff(c(0,out2$time))>0.0001)] = max(c(out2$I1,out2$iso1))

u_2.2 = rep(0,length(J2))
u_2.2[which(diff(c(out2$C2[1],out2$C2))*diff(c(0,out2$time))>0.001)] = max(c(out2$I2,out2$iso2))

out.circ <- data.frame(out2, u_2 = u_2, u_2.2 = u_2.2, j = J2)

#plot community infections
g.circ1 = ggplot(out.circ, aes(x = time, y = I1)) + 
  geom_ribbon(aes(ymin = 0, ymax = u_2), fill = cols[9], alpha = 0.2)+
  geom_line(color = cols[9], size = 2)+ 
  ggtitle("Circuit Breaker")+ylab("Community prevalence") + xlim(0,300)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.circ1

#plot travel cases
g.circ1.2 = ggplot(out.circ, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_2.2), fill = cols[9], alpha = 0.2)+
  geom_line(color = cols[9], size = 2)+
  ggtitle("Mitigation")+ylab("Traveller's prevalence") + xlim(0,300)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.circ1.2

gcs = g.circ1 + g.circ1.2
gcs


```





```{r}
#### CIRCUIT BREAKER

T <- 200

u1max <- 0.7
u2max <- 1.8

tstart1 <- 0
tstart2 <- 0

toff1<-20
toff2<-20

C1max <- 800
C2max <- 30

out3 <- ode(y = c(S=5000,I1=10,I2=0,C1=0,C2=0,iso1=0, iso2=0), parms = NULL, times = seq(0,T,.05), func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
out3 <- data.frame(out3)

out.circ2<-out3


J3 = cumsum(beta*out3$S*(out3$I1+c*out3$I2)*diff(c(0,out3$time)))

u_3 = rep(0,length(J3))
u_3[which(diff(c(out3$C1[1],out3$C1))*diff(c(0,out3$time))>0.0001)] = max(c(out3$I1,out3$iso1))

u_3.2 = rep(0,length(J3))
u_3.2[which(diff(c(out3$C2[1],out3$C2))*diff(c(0,out3$time))>0.001)] = max(c(out3$I2,out3$iso2))

out.circ2 <- data.frame(out3, u_3 = u_3, u_3.2 = u_3.2, j = J3)

#plot community infections
g.circ2 = ggplot(out.circ2, aes(x = time, y = I1)) + 
  geom_ribbon(aes(ymin = 0, ymax = u_3), fill = cols[4], alpha = 0.2)+
  geom_line(color = cols[4], size = 2)+
  ggtitle("Circuit breaker ")+ylab("Community prevalence") + xlim(0,150)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.circ2

#plot travel cases
g.circ2.2 = ggplot(out.circ2, aes(x = time, y = I2)) +
  geom_ribbon(aes(ymin = 0, ymax = u_3.2), fill = cols[4], alpha = 0.2)+
  geom_line(color = cols[4], size = 2)+
  ggtitle("Circuit breaker ")+ylab("Traveller's prevalence") + xlim(0,150)+theme_classic() +
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 20),     # Legend title size
  legend.text = element_text(size = 20) )      # Legend text size

g.circ2.2

gcirc = g.circ2 + g.circ2.2
gcirc


```



```{r}

figmixed = gsupp/gsc/gcs/gcirc + plot_annotation(tag_levels = 'a') & theme(plot.tag = element_text(size = 25))
figmixed

```

