---
title: "Code for Figure 3.2: The effect of the relative transmissibility of infected travelers, c, on com-
munity infection prevalence when an optimal control is implemented."
#output: A plot of U1_[u1max] against time for different values of c.
date: Aug 08, 2024
---


```{r}


require(deSolve)
require(ggplot2)
require(patchwork)
require(ggpubr)

cols <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#66CC99")

##### Parameters
u1max <- 0.8
U1max <- 1500
beta <- 0.0002
theta <- 2
mu <- 0.334
T <- 1200
tstart1 <- 0
toff1 <- 1500
Imin <- 1

# This is designed to trigger termination of the simulation when I1 <-1
rootfun <- function(t, y, parameters){
  I1 = y[2]
  y1 = Imin - I1 
  return(y1)
}

SI <- function(t, y, parameters) {
  S <- y[1]
  I1 <- y[2]
  I2 <- y[3]
  U1 <- y[4]
  u1<-u1max
    if(U1 > U1max){
    u1 = 0
  }
  
  dS <- -beta * S * (I1 + parameters$c * I2)
  dI1 <- beta * S * (I1 + parameters$c * I2) - mu * I1 - u1 * I1
  dI2 <- theta - 2 * mu * I2
  dU1 <- u1 * I1
  return(list(c(dS, dI1, dI2, dU1)))
}
```



```{r}
# Simulation for different values of c
cvec <- c(0, 0.05, 0.1, 0.2, 0.5, 1)
DataProb <- NULL

for (c in cvec) {
  parameters <- list(c = c)
  
  out1 <- ode(y = c(S = 5000, I1 = 10, I2 = theta/(2*mu), U1 = 0), parms = parameters, times = seq(0,T,.05),    func = SI, events = list(func = NULL, root = TRUE, terminalroot = 1), rootfun=rootfun)
  
  
  
  out1 <- data.frame(out1)
  J1 <- cumsum(beta * out1$S * (out1$I1 + c * out1$I2) * diff(c(0, out1$time)))
  u1 <- rep(0, length(J1))
  u1[which(diff(c(out1$U1[1], out1$U1)) * diff(c(0, out1$time)) > 0.001)] <- max(c(out1$I1, out1$iso))
  
  DataProb <- rbind(DataProb, data.frame(out1, u = u1, j = J1, c = c))
}

# Plotting
g.chap2prob2 <- ggplot(DataProb, aes(x = time, y = I1, color = factor(c))) +
  geom_hline(aes(yintercept = Imin), color = "black", linetype = "dashed")  +
  geom_line(size = 1.5) +
  #ggtitle("Effect of transmission from travelers to the community") + 
  ylab(expression(paste("Community prevalence, ",  I[1](t)))) + xlim(0, T) + 
  theme_classic() +
  scale_y_continuous(breaks = seq(min(out1$I1), max(out1$I1), by = 2)) +
  scale_x_continuous(breaks = seq(min(out1$time), max(out1$time), by = 100)) +
  scale_color_discrete(name = "c")+
  ylim(c(0,1000))+
  scale_y_log10()+
  annotate("text", x = 0.9*T, y = 1*Imin, label = "Imin", color = "black", size = 6)+
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 25),     # Legend title size
  legend.text = element_text(size = 25) )      # Legend text size
g.chap2prob2

```



```{r}
g.U1 <- ggplot(DataProb, aes(x = time, y = U1, color = factor(c))) +
  geom_line(size = 1) +
  geom_hline(aes(yintercept = U1max), color = "black", linetype = "dashed")  +
  annotate("text", x = 900, y = 0.9*U1max, label = expression(paste(U[1][max])), hjust = -0.1, vjust = -2, color = "black", size = 6) +
  ggtitle(" ") + ylab(expression(paste("Total isolated community members,",  U[1](t)))) + xlim(0, T) + theme_classic() +
  scale_color_discrete(name = "c") +
  scale_y_continuous(breaks = seq(min(out1$U1), max(out1$U1), by = 200)) +
  scale_x_continuous(breaks = seq(min(out1$time), max(out1$time), by = 100))+ 
  theme(
  plot.title = element_text(size = 20),       # Title size
  axis.title = element_text(size = 30),       # Axis title size
  axis.text = element_text(size = 30),        # Axis text size
  legend.title = element_text(size = 25),     # Legend title size
  legend.text = element_text(size = 25) )      # Legend text size
g.U1  
```

```{r}

chap2.prob2 <- g.chap2prob2 / g.U1 + plot_annotation(tag_levels = "a") & theme(plot.tag = element_text(size = 25))

chap2.prob2


```